[package]
name = "schemajs_config"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
resolver = "2"

[dependencies]
toml.workspace = true
serde.workspace = true
anyhow.workspace = true
paste.workspace = true