name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: schemejs
            asset_prefix: ubuntu
          - os: windows-latest
            artifact_name: schemejs.exe
            asset_prefix: windows
          - os: macos-13
            artifact_name: schemejs
            asset_prefix: macos
          - os: macos-latest
            artifact_name: schemejs
            asset_prefix: m1

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          ./scripts/release.sh
          ls target
          ls target/release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_prefix }}-${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
